---
name: Swap functional tests

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  job_functional_tests:
    uses: LedgerHQ/app-exchange/.github/workflows/reusable_swap_functional_tests.yml@cev/B2CA-1838_implement-swap
    with:
      branch_for_cardano: ${{ github.ref }}
      test_filter: '"ADA or ada or Cardano or cardano"'
